### ISSUE TITLE
Hue Entertainment - Lights not responding

### ISSUE THREAD

**Issue by WolfsWelpe** [hass-emulated-hue/core#69]
**Describe the bug**

Hello,
I just tried to set up the Hue entertainment areas. It works fine so far, you can set it up and save it. While arranging the lights, they react, but as soon as you get to the part about testing the synchronisation, the lights stay exactly as they were before. No change whatsoever. The lights can be controlled otherwise. (I have tried it with different lights, but the same thing happened with all of them).

**Steps to Reproduce**

1. Go To Settings
2. Click on Entertainment-Areas
3. Create Area
4. Select a Light
5. Arrange the light
6. Click on Next 2x

**Expected behavior**

The light symbols should light up in different colours in the app, but the lights remain the same as when they were arranged.

**Logs**

**Hardware Info:**
 - Architecture (Ex: x86, ARM): 
 - Addon version (Ex: stable or dev):  dev
    - Value of "tag_commit_or_branch" if using dev:  master
 - OS (Ex: Windows 10, Ubuntu Buster):  HassOS (Running in HyperV on Windows10)
 - Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero):  PC

**Additional context**

I'm trying to connect it to Razer Synapse, the lights are also recognised perfectly there, but none of the lights change no matter what I set.

**Comment by marcelveldt** [comment]
This issue has been fixed very recently. @alexyao2015 can you release a new version to the repo with all recent fixes ?
Perhaps also include the throttling fix PR...

**Comment by WolfsWelpe** [comment]
Hello,
I installed version 0.1.1 now and tried it again.
Unfortunately, the same behaviour as before.

**Comment by alexyao2015** [comment]
Please refer to #42. It doesn't work with the latest version of hue sync.

**Comment by WolfsWelpe** [comment]
But its still not responding inside the Hue App ?
And im using Razer Synapse not HueSync ??

**Comment by alexyao2015** [comment]
I'm unsure of what the issue here is. Does entertainment work in the hue app? Is this a razer synapse only issue?

**Comment by WolfsWelpe** [comment]
Thanks for opening again :)
So I'll explain from the beginning. The lights all work perfectly when you control them individually. Creating an entertainment area also basically works. But now comes the catch. When creating the entertainment area, the lights only work as far as you arrange them, they change colour there but as soon as you get to the step Test synchronisation, the lights remain in the colour they were when you arranged them. Normally they should start to glow in colour, just synchronously as displayed in the app. This is completely independent of Razer Synape or Hue Sync. It's just the original Hue app where Hue Entertainment can't control the lights when tested in the area. I have even tried it with original Philips Hue lights, with every light in Home Assistant the same result.

Extra: Razer Synapse connects perfectly with the virtual Hue Bridge and also recognises the areas and the lights in them. According to the logs, an entertainment stream also starts, but the lights do not react. However, this is a fundamental error rather than a fault of Razer Synapse.

**Comment by WolfsWelpe** [comment]
I also looked into the Home Assistant events during the entertainment stream. Home Assistant does not receive any commands from Emulated Hue to change any lights. So I don't think it's the Home Assistant installation or the hardware. (LED Strip with WLED or another lamp).
If I control the light individually in the Hue app, Home Assistant also receives the commands and is visible in events.
The stream does start but nothing happens.
![image](https://user-images.githubusercontent.com/17033125/104155094-bb023680-53e6-11eb-97ed-7906073ee123.png)

**Comment by marcelveldt** [comment]
I believe this is fixed in all recent PR's, that's why I requested a new addon version so @WolfsWelpe and others can give it a spin.,

**Comment by alexyao2015** [comment]
We did release a new version yesterday and it seems like it still has a problem since 0.1.1 still had the issue. Can you turn on verbose logging and post the logs?

**Comment by WolfsWelpe** [comment]
`[services.d] done.
[14:40:20] INFO: Starting Emulated Hue...
2021-01-11 14:40:20,647 INFO  emulated_hue.config -- Auto detected listen IP address is 192.168.2.104
2021-01-11 14:40:20,652 DEBUG getmac -- Raw MAC found: None
2021-01-11 14:40:20,653 DEBUG getmac -- Raw MAC found: 00:15:5d:a3:94:00
2021-01-11 14:40:20,653 DEBUG aiorun -- Entering run()
2021-01-11 14:40:20,655 DEBUG aiorun -- Creating default executor
2021-01-11 14:40:20,664 INFO  hass-client -- Connecting to hassio/homeassistant
2021-01-11 14:40:20,665 INFO  emulated_hue.api -- Started HTTP webserver on port 80
2021-01-11 14:40:20,686 INFO  emulated_hue.api -- Started HTTPS webserver on port 443
2021-01-11 14:40:20,686 DEBUG emulated_hue.discovery -- Starting mDNS/uPNP discovery broadcast...
2021-01-11 14:40:20,691 INFO  hass-client -- Connected to hassio/homeassistant
2021-01-11 14:40:20,700 DEBUG hass-client -- Received area registry.
2021-01-11 14:40:20,700 DEBUG hass-client -- Received device registry.
2021-01-11 14:40:20,700 DEBUG hass-client -- Received entity registry.
2021-01-11 14:40:28,259 DEBUG emulated_hue.discovery -- Serving SSDP discovery info to ('192.168.2.104', 57245)
2021-01-11 14:40:28,260 DEBUG emulated_hue.discovery -- Serving SSDP discovery info to ('192.168.2.104', 57245)
2021-01-11 14:40:28,262 DEBUG emulated_hue.discovery -- Serving SSDP discovery info to ('192.168.2.72', 50036)
2021-01-11 14:40:30,261 DEBUG emulated_hue.discovery -- Serving SSDP discovery info to ('192.168.2.104', 36291)
2021-01-11 14:40:30,261 DEBUG emulated_hue.discovery -- Serving SSDP discovery info to ('192.168.2.104', 36291)
2021-01-11 14:40:32,261 DEBUG emulated_hue.discovery -- Serving SSDP discovery info to ('192.168.2.104', 46851)
2021-01-11 14:40:32,261 DEBUG emulated_hue.discovery -- Serving SSDP discovery info to ('192.168.2.104', 46851)
2021-01-11 14:40:33,019 DEBUG emulated_hue.api -- [192.168.2.98] GET /api/nouser/config
2021-01-11 14:40:33,019 INFO  emulated_hue.config -- Link request detected - Use the Homeassistant frontend to confirm this link request.
2021-01-11 14:40:33,054 DEBUG emulated_hue.api -- [192.168.2.98] GET /api/04604706-5378-443f-92ac-afe9780ea769
2021-01-11 14:40:33,493 DEBUG emulated_hue.api -- [192.168.2.98] GET /api/04604706-5378-443f-92ac-afe9780ea769/lights
2021-01-11 14:40:33,623 DEBUG emulated_hue.api -- [192.168.2.98] GET /api/04604706-5378-443f-92ac-afe9780ea769/groups
2021-01-11 14:40:33,635 DEBUG emulated_hue.api -- [192.168.2.98] GET /api/04604706-5378-443f-92ac-afe9780ea769/sensors
2021-01-11 14:40:33,645 DEBUG emulated_hue.api -- [192.168.2.98] GET /api/04604706-5378-443f-92ac-afe9780ea769/config
2021-01-11 14:40:34,407 DEBUG emulated_hue.api -- [192.168.2.98] GET /api/04604706-5378-443f-92ac-afe9780ea769/sensors
2021-01-11 14:40:34,418 DEBUG emulated_hue.api -- [192.168.2.98] GET /api/04604706-5378-443f-92ac-afe9780ea769/config
2021-01-11 14:40:34,437 DEBUG emulated_hue.api -- [192.168.2.98] GET /api/04604706-5378-443f-92ac-afe9780ea769/lights
2021-01-11 14:40:34,451 DEBUG emulated_hue.api -- [192.168.2.98] GET /api/04604706-5378-443f-92ac-afe9780ea769/groups
2021-01-11 14:40:36,607 DEBUG emulated_hue.api -- [192.168.2.98] GET /api/04604706-5378-443f-92ac-afe9780ea769/lights
2021-01-11 14:40:36,633 DEBUG emulated_hue.api -- [192.168.2.98] GET /api/04604706-5378-443f-92ac-afe9780ea769/groups
2021-01-11 14:40:37,900 DEBUG emulated_hue.api -- [192.168.2.98] GET /api/04604706-5378-443f-92ac-afe9780ea769/sensors
2021-01-11 14:40:37,917 DEBUG emulated_hue.api -- [192.168.2.98] GET /api/04604706-5378-443f-92ac-afe9780ea769/config
2021-01-11 14:40:38,442 DEBUG emulated_hue.api -- [192.168.2.98] GET /api/04604706-5378-443f-92ac-afe9780ea769/config
2021-01-11 14:40:39,408 DEBUG emulated_hue.api -- [192.168.2.98] GET /api/04604706-5378-443f-92ac-afe9780ea769/capabilities
2021-01-11 14:40:39,461 DEBUG emulated_hue.api -- [192.168.2.98] GET /api/04604706-5378-443f-92ac-afe9780ea769/sensors
2021-01-11 14:40:39,473 DEBUG emulated_hue.api -- [192.168.2.98] GET /api/04604706-5378-443f-92ac-afe9780ea769/config
2021-01-11 14:40:39,488 DEBUG emulated_hue.api -- [192.168.2.98] GET /api/04604706-5378-443f-92ac-afe9780ea769/lights
2021-01-11 14:40:39,515 DEBUG emulated_hue.api -- [192.168.2.98] GET /api/04604706-5378-443f-92ac-afe9780ea769/groups
2021-01-11 14:40:39,559 DEBUG emulated_hue.api -- [192.168.2.98] GET /api/04604706-5378-443f-92ac-afe9780ea769/capabilities
2021-01-11 14:40:41,331 DEBUG emulated_hue.discovery -- Serving SSDP discovery info to ('192.168.2.1', 60912)
2021-01-11 14:40:41,337 DEBUG emulated_hue.discovery -- Serving SSDP discovery info to ('192.168.2.51', 37204)
2021-01-11 14:40:42,543 DEBUG emulated_hue.api -- [192.168.2.98] PUT /api/04604706-5378-443f-92ac-afe9780ea769/lights/5/state
2021-01-11 14:40:42,544 DEBUG emulated_hue.api -- {'alert': 'select'}
2021-01-11 14:40:46,333 DEBUG emulated_hue.discovery -- Serving SSDP discovery info to ('192.168.2.1', 60912)
2021-01-11 14:40:46,340 DEBUG emulated_hue.discovery -- Serving SSDP discovery info to ('192.168.2.51', 37204)
2021-01-11 14:40:47,359 DEBUG emulated_hue.api -- [192.168.2.98] PUT /api/04604706-5378-443f-92ac-afe9780ea769/lights/5/state
2021-01-11 14:40:47,361 DEBUG emulated_hue.api -- {'on': True, 'bri': 254, 'xy': [0.5865, 0.3944]}
2021-01-11 14:40:48,380 DEBUG emulated_hue.api -- [192.168.2.98] PUT /api/04604706-5378-443f-92ac-afe9780ea769/lights/5/state
2021-01-11 14:40:48,382 DEBUG emulated_hue.api -- {'on': True, 'alert': 'lselect', 'bri': 254, 'xy': [0.3129, 0.3291]}
2021-01-11 14:40:49,595 DEBUG emulated_hue.api -- [192.168.2.98] GET /api/04604706-5378-443f-92ac-afe9780ea769/config
2021-01-11 14:40:51,336 DEBUG emulated_hue.discovery -- Serving SSDP discovery info to ('192.168.2.1', 60912)
2021-01-11 14:40:51,340 DEBUG emulated_hue.discovery -- Serving SSDP discovery info to ('192.168.2.51', 37204)
2021-01-11 14:40:52,406 DEBUG emulated_hue.api -- [192.168.2.98] PUT /api/04604706-5378-443f-92ac-afe9780ea769/lights/5/state
2021-01-11 14:40:52,407 DEBUG emulated_hue.api -- {'on': True, 'alert': 'none', 'bri': 254, 'xy': [0.3138, 0.592]}
2021-01-11 14:40:53,461 DEBUG emulated_hue.api -- [192.168.2.98] PUT /api/04604706-5378-443f-92ac-afe9780ea769/lights/5/state
2021-01-11 14:40:53,462 DEBUG emulated_hue.api -- {'on': True, 'alert': 'lselect', 'bri': 254, 'xy': [0.3129, 0.3291]}
2021-01-11 14:40:54,041 DEBUG emulated_hue.api -- [192.168.2.98] PUT /api/04604706-5378-443f-92ac-afe9780ea769/lights/5/state
2021-01-11 14:40:54,042 DEBUG emulated_hue.api -- {'on': True, 'alert': 'none', 'bri': 254, 'xy': [0.3138, 0.592]}
2021-01-11 14:40:56,336 DEBUG emulated_hue.discovery -- Serving SSDP discovery info to ('192.168.2.1', 60912)
2021-01-11 14:40:56,340 DEBUG emulated_hue.discovery -- Serving SSDP discovery info to ('192.168.2.51', 37204)
2021-01-11 14:40:56,344 DEBUG emulated_hue.api -- [192.168.2.98] POST /api/04604706-5378-443f-92ac-afe9780ea769/groups
2021-01-11 14:40:56,345 DEBUG emulated_hue.api -- {'name': 'Entertainment-Bereich 1', 'lights': ['5'], 'type': 'Entertainment', 'class': 'TV', 'locations': {'5': [0.038095, 0.54127, 0]}, 'stream': {'proxymode': 'auto'}}
2021-01-11 14:40:56,400 DEBUG emulated_hue.api -- [192.168.2.98] PUT /api/04604706-5378-443f-92ac-afe9780ea769/groups/5
2021-01-11 14:40:56,401 DEBUG emulated_hue.api -- {'stream': {'active': True}}
2021-01-11 14:40:56,401 DEBUG emulated_hue.api -- Start Entertainment mode for group 5 - params: {'stream': {'active': True}}
2021-01-11 14:40:56,402 INFO  emulated_hue.entertainment -- Start HUE Entertainment Service on UDP port 2100.
2021-01-11 14:40:56,650 DEBUG emulated_hue.api -- [192.168.2.98] GET /api/04604706-5378-443f-92ac-afe9780ea769/lights
2021-01-11 14:40:56,684 DEBUG emulated_hue.api -- [192.168.2.98] GET /api/04604706-5378-443f-92ac-afe9780ea769/groups
2021-01-11 14:40:58,731 DEBUG emulated_hue.api -- [192.168.2.98] GET /api/04604706-5378-443f-92ac-afe9780ea769/lights
2021-01-11 14:40:58,766 DEBUG emulated_hue.api -- [192.168.2.98] GET /api/04604706-5378-443f-92ac-afe9780ea769/groups
2021-01-11 14:40:59,809 DEBUG emulated_hue.api -- [192.168.2.98] GET /api/04604706-5378-443f-92ac-afe9780ea769/config
2021-01-11 14:41:00,844 DEBUG emulated_hue.api -- [192.168.2.98] GET /api/04604706-5378-443f-92ac-afe9780ea769/lights
2021-01-11 14:41:00,880 DEBUG emulated_hue.api -- [192.168.2.98] GET /api/04604706-5378-443f-92ac-afe9780ea769/groups
2021-01-11 14:41:01,338 DEBUG emulated_hue.discovery -- Serving SSDP discovery info to ('192.168.2.1', 60912)
2021-01-11 14:41:01,342 DEBUG emulated_hue.discovery -- Serving SSDP discovery info to ('192.168.2.51', 37204)
2021-01-11 14:41:02,139 DEBUG emulated_hue.api -- [192.168.2.98] PUT /api/04604706-5378-443f-92ac-afe9780ea769/groups/5
2021-01-11 14:41:02,141 DEBUG emulated_hue.api -- {'stream': {'active': True}}
2021-01-11 14:41:02,141 DEBUG emulated_hue.api -- Start Entertainment mode for group 5 - params: {'stream': {'active': True}}
2021-01-11 14:41:02,934 DEBUG emulated_hue.api -- [192.168.2.98] GET /api/04604706-5378-443f-92ac-afe9780ea769/lights
2021-01-11 14:41:02,970 DEBUG emulated_hue.api -- [192.168.2.98] GET /api/04604706-5378-443f-92ac-afe9780ea769/groups
2021-01-11 14:41:05,010 DEBUG emulated_hue.api -- [192.168.2.98] GET /api/04604706-5378-443f-92ac-afe9780ea769/lights
2021-01-11 14:41:05,086 DEBUG emulated_hue.api -- [192.168.2.98] GET /api/04604706-5378-443f-92ac-afe9780ea769/groups
2021-01-11 14:41:07,170 DEBUG emulated_hue.api -- [192.168.2.98] GET /api/04604706-5378-443f-92ac-afe9780ea769/lights
2021-01-11 14:41:07,204 DEBUG emulated_hue.api -- [192.168.2.98] GET /api/04604706-5378-443f-92ac-afe9780ea769/groups
2021-01-11 14:41:09,247 DEBUG emulated_hue.api -- [192.168.2.98] GET /api/04604706-5378-443f-92ac-afe9780ea769/lights
2021-01-11 14:41:09,285 DEBUG emulated_hue.api -- [192.168.2.98] GET /api/04604706-5378-443f-92ac-afe9780ea769/groups
2021-01-11 14:41:09,832 DEBUG emulated_hue.api -- [192.168.2.98] GET /api/04604706-5378-443f-92ac-afe9780ea769/config
2021-01-11 14:41:10,676 DEBUG emulated_hue.api -- [192.168.2.98] PUT /api/04604706-5378-443f-92ac-afe9780ea769/groups/5/action
2021-01-11 14:41:10,677 DEBUG emulated_hue.api -- {'on': True, 'bri': 77, 'xy': [0.4584, 0.41]}
2021-01-11 14:41:10,677 INFO  emulated_hue.api -- Stop Entertainment mode for group 5 - params: {'on': True, 'bri': 77, 'xy': [0.4584, 0.41]}
2021-01-11 14:41:10,678 INFO  emulated_hue.entertainment -- HUE Entertainment Service stopped.
2021-01-11 14:41:11,374 DEBUG emulated_hue.api -- [192.168.2.98] GET /api/04604706-5378-443f-92ac-afe9780ea769/lights
2021-01-11 14:41:11,416 DEBUG emulated_hue.api -- [192.168.2.98] GET /api/04604706-5378-443f-92ac-afe9780ea769/groups
2021-01-11 14:41:12,204 DEBUG emulated_hue.api -- [192.168.2.98] GET /api/04604706-5378-443f-92ac-afe9780ea769/capabilities`

Here you go.
I created an Entertainment Area and added 1 Light.
Behaviour as explained earlier

**Comment by alexyao2015** [comment]
I see that you mentioned that this also doesn't work with the official hue setup. What lights are you using? I am unable to reproduce this issue as it's working perfectly fine on my end. Did you try the latest version 0.1.2?

**Comment by WolfsWelpe** [comment]
Yes I installed 0.1.2.
I have selected a ceiling light that is connected to the original Hue Bridge and set up in Home Assistant. This only reacts when arranging and then no longer reacts when testing the area. 
Home Assistant also does not receive any commands from the addon to change any lights. So it can't be the hardware. Does a certain port have to be released or something else? But since Home Assistant receives the commands when arranging the lights in Hue Entertainment, I wonder why it doesn't work in area testing.

**Comment by WolfsWelpe** [comment]
These Addons are currently installed: 
![image](https://user-images.githubusercontent.com/17033125/104190972-2a931880-541d-11eb-8e02-4f41381b4c5c.png)

**Comment by alexyao2015** [comment]
Does the light function when you could it from Home Assistant? Does the light function when you control it through the Hue app?

**Comment by WolfsWelpe** [comment]
Yes and yes

**Comment by WolfsWelpe** [comment]
Here I controlled the same light as assigned in the Entertainment Area: https://pastebin.com/6pRkChQc

**Comment by WolfsWelpe** [comment]
Excuse me, but am I doing something fundamentally wrong? Because then I don't see what at all.

**Comment by alexyao2015** [comment]
I don't see what the issue is here either... It all works fine for me. Try pasting these fake lights into your configuration and see if they work in entertainment mode.
https://github.com/hass-emulated-hue/dev-kit/blob/1e8d34b1cac70250b468faed1d231ec0b2544ad2/lights.yaml#L1

**Comment by WolfsWelpe** [comment]
Ok I tried it. Same behaviour as for my lamps. Home Assistant not receiving any Events or commands from the Addon :/

**Comment by WolfsWelpe** [comment]
https://photos.app.goo.gl/UaiaBMESNZHrTCHP9
Ok I have recorded a small video of how I create the area with the two lamps. Both lamps react and I can also see it in Home Assistant. As soon as I press to arrange them, I see events in the Home Assistant console. As soon as I test the area at the end, nothing happens. Normally, the lamps and Home Assistant should receive many commands to change the fake lights. Unfortunately, nothing comes through.

**Comment by alexyao2015** [comment]
I just wanted to mention, you won't see the lights turning on or changing color during entertainment mode with those fake lights. During entertainment mode, you should see the brightness input number sliding back and forth. You should also be able to manually control the fake lights as well in HA and the Hue app.

**Comment by WolfsWelpe** [comment]
Correct. Im able to control the lights in the hue app and in Home Assistant. (THe Fake lights).
Yeah and I watched the event stream of Home Assistant there is no event reducing the brightness of the fake lamps during the
entertainment mode. (Just a question do you know what I mean with the event stream?)

**Comment by WolfsWelpe** [comment]
It would be so much easier If I can just show you these things D: Sadly the language is a little barrier ^^ 
You don't speak German, do you?

**Comment by alexyao2015** [comment]
Occasionally I have seen that behavior at the beginning of the video but at the end when the lights are changing color, it should also be changing in HASS. Not sure what event stream you are referring to. Try manually using a service to set the brightness of the fake RGBWW light. Thats all we do internally.

> You don't speak German, do you?

Unfortunately, not.

**Comment by Kvanr23** [comment]
I believe I have the same problem with Razer Synapse, when setting up the Entertainment Area in the Hue app, everything goes well.
Until the 'Test synchronization' page, here the lights cycle through the rgb colors in the app.
The physical lights (or the fake lights) are supposed to change with these, but they don't.

->Hass lights are not responding to, and updating with the entertainment mode.

**Comment by WolfsWelpe** [comment]
Ok I don't know how else to explain it D:
If the lamps at the end of the video change colours, they should also do so correctly in HASS, but they do not. This is because no commands are sent from the addon when the entertainment module in the addon does it. If I manually change something in HASS itself or in the Hue app, it works fine and I get an event report.
Example: 
![image](https://user-images.githubusercontent.com/17033125/104199702-0c7ee580-5428-11eb-8668-27081db3b57f.png)
But when the entertainment module tries to change the lamps, they do not synchronise and HASS does not receive a request to change a lamp and therefore no event report.

**Comment by alexyao2015** [comment]
Lets take Razer Synapse out of the mix. So to be clear, you:
1) Have no issues controlling the fake and real light in HASS and the Hue app through the emulator
2) Have issues with lights changing color through the test entertainment functionality in the Hue app

Try using developer tools with the service `light.turn_on`
```
entity_id: light.actual_entity_id
brightness: 200
xy_color: [.12,.9]
```
If nothing happens, remove xy_color. If still nothing happens, remove both brightness and xy_color to see if the light just turns on.

**Comment by WolfsWelpe** [comment]
1. Correct
2. Correct

Tried your command it is working perfectly fine. It turned green and got  bright

**Comment by WolfsWelpe** [comment]
But as I said earlier.
It is not a problem with Hass or the Hardware.
The Entertainment Module is just not sending any PUT command or with whatever you tell HASS to change the light.

**Comment by marcelveldt** [comment]
This might be a race condition. I've just put up a small patch in a PR

**Comment by WolfsWelpe** [comment]
> This might be a race condition. I've just put up a small patch in a PR

How do I install the PR in Home Assistant for testing ?

**Comment by WolfsWelpe** [comment]
Ok just a question how is the entertainment module telling hass to change a light? Is it a simple PUT Request and is it logged in the normal Addon Log Window? I just installed your PR marcel sadly no success.
Just recreated the entertainment Area and I found out that there is not a single put request going out when test the area.
![image](https://user-images.githubusercontent.com/17033125/104202706-8a90bb80-542b-11eb-8779-b1c905b3065c.png)

**Comment by marcelveldt** [comment]
There's a websocket connection to HA as it is low latency.
So you will not see these requests over the line and especially not PUT requests as that will have A LOT of overhead.

I will test this tonight when I get home from work on my own Philips TV with Ambilight+HUE so I can fix whatever I see.

BTW: I you want to know if the emulated hue is sending/controlling the light you can watch the "call_service" event from dev tools in HA.

**Comment by WolfsWelpe** [comment]
Yes I honestly tried that already with the event stream listening.
Sadly not a single request is coming through when testing the area.

**Comment by marcelveldt** [comment]
Ah thanks for that confirmation. I'll do some investigating on my own setup

**Comment by lagmoellertim** [comment]
Just wanted to mention that I seem to have the same problem, I already mentioned it in #61 (there is also my setup listed if you need that). For me Control over Hue is working great as long as I don't use entertainment mode. When I activate it, nothing happens (lights stay the same) and after it is ended all lights can be controlled again via non-entertainment actions. 
For me, call_service also doesn't log any calls while entertainment mode is running.
If needed, I can contribute further logs or other things to help debugging.

I'm using YeeLights, WLEDs and virtual light groups if that helps.

**Comment by alexyao2015** [comment]
Good news, I've managed to reproduce the issue. Bad news, it seems that the issue is only reproducible within the addon itself and does not occur in a development environment. 

It appears that entertainment packets are not being received even though the openssl binary is starting without issues. I would think that this would be a docker networking issue, but we are running host networking, so that shouldn't be an issue. Will definitely need to do more investigation.

**Comment by alexyao2015** [comment]
I see UDP packets definitely hitting HA, but for some reason we are unable to receive any packets. Further testing with nmap showed that port 2100 indeed does become open when entertainment is started and closes when entertainment ends. Likely does not appear to be an issue attaching to the port, but rather an issue obtaining the data from the openssl binary. 

@marcelveldt Any thoughts on this?

**Comment by marcelveldt** [comment]
It's exactly what I was seeing on my own setup. If I still had hair, I was pulling it out now.
It runs perfectly fine when I run it on my development Macbook but as soon as I run it from the HA addon (docker) it breaks.

There is one thing that just pops up in my head. Previously we had a fixed mac address for docker images, now it uses the host mac address, maybe that is the issue ?

**Comment by alexyao2015** [comment]
For those of you facing this issue, what was the last version where this worked or was this always an issue?

**Comment by WolfsWelpe** [comment]
It never worked for me sadly ^^ The last time I was not even able to create the Hue Entertainment Area and as soon as I was able to create one I had this Issue.

**Comment by Kvanr23** [comment]
Never worked for me either.

**Comment by lagmoellertim** [comment]
Same for me, Entertainment mode is not working in any version for me

**Comment by WolfsWelpe** [comment]
Heyy, so something new?

**Comment by marcelveldt** [comment]
No yet, a bit busy with work atm. I"ll take a look at it this evening. It did work once so I'm pretty sure we can fix this.

**Comment by Sapd** [comment]
> I believe I have the same problem with Razer Synapse, when setting up the Entertainment Area in the Hue app, everything goes well.
> Until the 'Test synchronization' page, here the lights cycle through the rgb colors in the app.
> The physical lights (or the fake lights) are supposed to change with these, but they don't.
> 
> ->Hass lights are not responding to, and updating with the entertainment mode.

I did a complete fresh install of everything, I use Hue bulbs, the Hue app and I experience 1:1 the same behaviour.

**Comment by marcelveldt** [comment]
Yeah, if you look one message above yours you could see that we're still have to look into the issue ;-)

**Comment by marcelveldt** [comment]
After a lot of trial and error we've narrowed the issue down to an issue specific in the docker image.
It works okay on our dev machines but not in the docker image. We'll provide a new docker image (and HA addon) asap to fix the issue.

**Comment by WolfsWelpe** [comment]
> After a lot of trial and error we've narrowed the issue down to an issue specific in the docker image.
> It works okay on our dev machines but not in the docker image. We'll provide a new docker image (and HA addon) asap to fix the issue.

Very nice :D Looking forward to pairing it with Razer Synapse :D

**Comment by alexyao2015** [comment]
If its not pairing, it might be another issue, potentially related to #42. The issue we are specifically targeting here is related to entertainment pairing and activating, but no lights responding. Hope to have a resolution for this soon!

**Comment by WolfsWelpe** [comment]
> If its not pairing, it might be another issue, potentially related to #42. The issue we are specifically targeting here is related to entertainment pairing and activating, but no lights responding. Hope to have a resolution for this soon!

Sorry my bad ^^ I have expressed myself incorrectly
Of course I meant that the lights on Razer Synapse then react :) It already connects perfectly and the entertainment areas are also recognised perfectly :)

**Comment by alexyao2015** [comment]
We've added a temporary fix for this issue in the latest stable build.

**Comment by WolfsWelpe** [comment]
> We've added a temporary fix for this issue in the latest stable build.

You mean in 2.0 ?

**Comment by alexyao2015** [comment]
The stable addon has a new update which should fix it.

**Comment by WolfsWelpe** [comment]
I tried it :OOOO Its working damn fine :D Very responsive but a little delayed but otherwise good :D

**Comment by alexyao2015** [comment]
The delay is very dependant on the type of lights you're using. Esphome lights would have the lowest latency. Other lights may or may not be as fast.

**Comment by WolfsWelpe** [comment]
Well Im using WLED, is there a setting I should change (By the way WLED is supporting UDP Stream maybe this is useful?)

**Comment by alexyao2015** [comment]
Maybe? That would be up to you to research/ask elsewhere. The latency you are seeing is between Hass and the lights. Ask the integration developer to provide a low latency connection.

**Comment by WolfsWelpe** [comment]
Ohhhh Alex,
I found another thing. Like I changed the behaviour what should happen when the stream stops.
I changed it to "Turn Off" but nothing happens when I stop the stream.
Like the lettering under the name of the Entertainment Area disappears an reappears again when I start or stop the stream but the lights wont turn off :(

**Comment by alexyao2015** [comment]
Yeah that's a feature that isn't currently supported yet

**Comment by WolfsWelpe** [comment]
Ok :D
Is there any way to intercept HomeAssistant when the entertainment stream stops? It is noted in the logs of the addon, is there an event which is sent to HomeAssistant?

And I wanted to thank you guys so much for developing this addon :D

**Comment by Kvanr23** [comment]
I am using Esphome for my led strip and it does connect and setup/works correctly, with no delays when using it as 1 light.
However, I partitioned my led strip into 5 lights as well, and when I try to create an entertainment zone with those 5 instead of the 1 strip, I get the same delays as WolfsWelpe.

**Comment by marcelveldt** [comment]
We will look into addressing esphome lights directly on UDP but for now we'll have to do with the current implementation.
Entertainment mode sends a very high load of light commands to the lights and both HA as lights have to cope up with that.
In the emulated_hue.json you can set the throttle setting for each light. For example set it to 500 (=500ms) for your lights and see if that makes a difference

**Comment by WolfsWelpe** [comment]
Ok I will give it a try.
So maybe could you send an event to HomeAssistant when the Entertainment Stream start or stop?
That would help me to do a few automations without the indirect way through the addon logs if it is not too much effort.

**Comment by marcelveldt** [comment]
OK, I'll add an event.

**Comment by alexyao2015** [comment]
There is an open request for an event in #64 btw

**Comment by WolfsWelpe** [comment]
I just got a new Error: https://pastebin.com/3Rh4YPB5

Well I did this:
I connected Razer Synapse and all worked fine, I restarted my PC so maybe Razer Synapse didnt disconnect properly from the Hue Bridge, now Razer Synapse is not able to connect again, only if I restart the Addon it is able.

 If I disconnect the Hue Bridge in Razer Synapse it is working fine and it is able to connect again.

**Comment by alexyao2015** [comment]
As of 0.2.1, this issue is now fixed! 🎉 

If you have any other issues, please open a new issue/discussion.
